name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Lean and cache dependencies
      - name: Install Lean
        uses: leanprover/lean-action@v1
        with:
          # This is the updated line
          use-github-cache: true

      # Step 3: Build the project and check proofs
      - name: Build project
        run: lake build
